version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - "2358:2358"
    depends_on:
      - db
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/workers", "--count=2"]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2.4
    command: ["bash", "-c", "docker-entrypoint.sh --appendonly no"]
    restart: always

volumes:
  data:
