x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    cpus: 0.5  # Giới hạn CPU cho server
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers", "--count=1"]  # Giảm số lượng worker xuống 1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    cpus: 0.7  # Giới hạn CPU cho worker
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: ["bash", "-c", "docker-entrypoint.sh --appendonly no"]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
